<% require 'kitchen-sync' %>
---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-7.1
  driver_plugin: ec2
  driver_config:
    username: <%= ENV['AWS_CLOUD_USER'] %>
    image_id: <%= ENV['AWS_CLOUD_AMI'] %>
    flavor_id: <%= ENV['AWS_INSTANCE_TYPE'] %>

suites:

- name: default
  run_list:
    - recipe[taurus::default]
  attributes: {}
